# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='category_pics')),
            ],
        ),
        migrations.CreateModel(
            name='IncredientInStore',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('normal_units', models.IntegerField()),
                ('measure_units', models.CharField(choices=[('KG', 'red'), ('LT', 'lt'), ('No', 'no')], max_length=10)),
                ('availableUnits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='product_pics')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
                ('increadients', models.ManyToManyField(to='products.IncredientInStore')),
            ],
        ),
        migrations.CreateModel(
            name='WhareHouse',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('normalrange', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
            ],
        ),
    ]
