# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incredientinstore',
            name='measure_units',
            field=models.CharField(choices=[('KG', 'kg'), ('LT', 'litre'), ('No', 'No')], max_length=10),
        ),
    ]
