# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avilableForSell',
            field=models.IntegerField(default=0),
        ),
    ]
