# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180131_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
