# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180131_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='SalesReportTransaction',
        ),
    ]
