# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180131_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
