# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180131_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereport',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='storereport',
            name='time',
            field=models.TimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesreporttransaction',
            name='saleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleid', to='products.SalesReport'),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
