# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180131_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
