# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180131_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wharehousereport',
            name='reasons',
            field=models.CharField(choices=[('CREATED AFRER CREATE IN STORE', 'C'), ('REMOVED ONLY FROM WHAREHOUSE', 'R'), ('REMOVED AFTER REMOVED IN STORE WHAREHOUSE ', 'RS'), ('NCREADIENT ADDED TO STORE', 'RED'), ('INCREASE FROM INPORT', 'A')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='status',
            field=models.CharField(choices=[('CREATED', 'C'), ('REMOVED', 'R'), ('REDUCED', 'RE'), ('ADDED', 'A')], max_length=50),
        ),
    ]
