# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180203_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wharehousereport',
            old_name='amount',
            new_name='availableAfter',
        ),
        migrations.AddField(
            model_name='wharehousereport',
            name='availableBefore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wharehousereport',
            name='normalAfter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wharehousereport',
            name='normalBefore',
            field=models.IntegerField(default=0),
        ),
    ]
