# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180203_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
