# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20180205_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
