# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20180205_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='status',
            field=models.CharField(choices=[('CREATED', 'C'), ('REMOVED', 'R'), ('REDUCED', 'RE'), ('ADDED', 'A')], max_length=50),
        ),
    ]
