# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180205_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='status',
            field=models.CharField(choices=[('CREATED', 'C'), ('REMOVED', 'R'), ('REDUCED', 'RE'), ('A', 'ADDED')], max_length=50),
        ),
    ]
