# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180205_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageralert',
            name='phoneNumber',
            field=models.CharField(max_length=50),
        ),
    ]
