# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20180206_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wharehousereport',
            name='time',
        ),
    ]
