# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_remove_wharehousereport_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wharehousereport',
            name='daten',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
