# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_wharehousereport_daten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereport',
            name='time',
        ),
        migrations.AddField(
            model_name='storereport',
            name='daten',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
