# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20180206_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='wharehousereport',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
