# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20180206_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='daten',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
