# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20180207_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageralert',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manageralert',
            name='phoneNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='amount',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='availableAfter',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='availableBefore',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='normalAfter',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='normalBefore',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
