# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20180207_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wharehousereport',
            name='availableAfter',
            field=models.CharField(default='___', max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='availableBefore',
            field=models.CharField(default='___', max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='normalAfter',
            field=models.CharField(default='___', max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='normalBefore',
            field=models.CharField(default='___', max_length=50),
        ),
    ]
