# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20180208_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageralert',
            name='id',
            field=models.IntegerField(primary_key=True),
        ),
    ]
