# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20180208_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageralert',
            name='id',
        ),
    ]
