# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20180208_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageralert',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
