# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20180209_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incredientinstore',
            name='measure_units',
            field=models.CharField(choices=[('_Kg', '_Kg'), ('_Lt', '_Lt'), ('_Count', '_Count')], max_length=10),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('REMOVED', 'REMOVED'), ('REDUCED', 'REDUCED'), ('ADDED', 'ADDED')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='reasons',
            field=models.CharField(choices=[('CREATED AFRER CREATE IN STORE', 'CREATED AFRER CREATE IN STORE'), ('REMOVED ONLY FROM WHAREHOUSE', 'REMOVED ONLY FROM WHAREHOUS'), ('REMOVED AFTER REMOVED IN STORE', 'REMOVED AFTER REMOVED IN STORE'), ('NCREADIENT ADDED TO STORE', 'NCREADIENT ADDED TO STORE'), ('INCREASE DIRECT', 'INCREASE DIRECT'), ('MAKE CHANGES TO BOTH NORMAL AND AVAILABLE UNITS', 'MAKE CHANGES TO BOTH NORMAL AND AVAILABLE UNITS'), ('CREATED AGAIN AFTER EDIT IN STORE', 'CREATED AGAIN AFTER EDIT IN STORE'), ('CREATED NEW AFTER EDIT IN STORE', 'CREATED NEW AFTER EDIT IN STORE'), ('MAKE CHANGE TO NORMAL UNITS', 'MAKE CHANGE TO NORMAL UNITS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wharehousereport',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('REMOVED', 'REMOVED'), ('REDUCED', 'REDUCED'), ('ADDED', 'ADDED'), ('CHANGES', 'CHANGES')], max_length=50),
        ),
    ]
