# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20180210_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incredientinstore',
            name='measure_units',
            field=models.CharField(choices=[('_Kg', '_Kg'), ('_Lt', '_Lt'), ('_Count', '_Count'), ('_Mkungu', '_Mkungu')], max_length=10),
        ),
    ]
